### ISSUE TITLE
EPIPE and ECONNRESET errors

### ISSUE THREAD

**Issue by aomarks** [Polymer/tachometer#72]
Errors like this get logged to the terminal sometimes:

```
Error: write EPIPE
      at WriteWrap.afterWrite (net.js:836:14)

Error: read ECONNRESET
      at TCP.onread (net.js:660:25)
```

It doesn't crash the runner, and doesn't seem to affect the result, just logs. The reported case was a large site, with many files, some of which were large.

**Comment by aomarks** [comment]
Never figured out why this was happening or got a reliable repro, but haven't had any reports lately. Closing for now.
